### ISSUE TITLE
NPM command not found

### ISSUE THREAD

**Issue by wiedo** [bvodola/meteorfaction#1]
In the 'Files extracted. Installing app dependencies... --silent' step I get the error:
`bash: npm: command not found`

If I SSH to my server and run:
`cd ~/webapps/appdir/bundle/programs/server && npm install --silent && cd ../../../bin && rm start`
it works perfectly but if I don't connect to SSH first and run:
`ssh user@server.webfaction.com "cd ~/webapps/appdir/bundle/programs/server && npm install --silent && cd ../../../bin && rm start"`
I get the same error. What am I doing wrong?

**Comment by bvodola** [comment]
That's weird. I'll try to reproduce and get back to you! 
It's been a while. Have you solved the issue, by the way?

**Comment by wiedo** [comment]
I managed to get my meteor site running on the server manually, but didn't with your script. Wish I could use your script though because it's a lot of commands to just update a website (especially frustrated when I made a typo on my website 🤦🏼‍♂️)
